INSERT INTO USER (ID, NAME, EMAIL, PASSWORD) VALUES(1, 'Teste', 'teste@email.com', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');

INSERT INTO SOCCER_PLAYER (ID, NAME, POSITION, HEIGHT, AGE, HOMETOWN) VALUES (1, 'Cássio', 'GOLEIRO', '1,95', 32, 'Veranópolis');